image: python:3.6.5

cache:
  paths:
    - tests/vcr
    - .pip

before_script:
  - pip --cache-dir=.pip install -r requirements.txt

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python -munittest tests/*.py tests/*/*.py

deploy:
  stage: deploy
  type: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H '167.99.210.104' >> ~/.ssh/known_hosts
    - git push dokku@167.99.210.104:autormtk master
  only:
    - master
