image: python:3.6.5

before_script:
  - pip install -r requirements.txt
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H '167.99.210.104' >> ~/.ssh/known_hosts

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python -munittest tests/**/**.py

deploy:
  stage: deploy
  type: deploy
  script:
    - git push dokku@167.99.210.104:autormtk master
  only:
    - master
