image: python:3.6.5

before_script:
  - pip install -r requirements.txt

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python -munittest test/**/**.py

deploy:
  stage: deploy
  type: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
